### PR TITLE
Just some typos to fix

### PR DESCRIPTION
**Pull request by ACollectionOfAtoms**

### CODE REVIEW

**Comment by ACollectionOfAtoms** [comment]
CI failing for typo fix? :sadcat:

**Comment by gustawlippa** [comment]
Hi!
Thank you for your contribution! Not only a good typo catch but it exposed problems on the CI, so twice the profit. For now I've pushed a quick fix in #119 but we'll keep a closer eye for OTP versions in the future. That PR is already merged, so if you rebase onto master, all should be green and I will be able to merge your fix.

**Comment by ACollectionOfAtoms** [comment]
@gustawlippa should be good 2 go!

**Comment by gustawlippa** [comment]
Thanks! 👍

**Pull request merged**
